# Generated by Django 2.0.6 on 2018-06-03 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("tenants", "0001_initial"), ("polls", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="choice",
            name="tenant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.Tenant",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="poll",
            name="tenant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.Tenant",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vote",
            name="tenant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.Tenant",
            ),
            preserve_default=False,
        ),
    ]
